In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

feature_name_df = pd.read_csv('./UCI HAR Dataset/features.txt', sep='\s+',
                              header=None, names=['column_index', 'column_name'])
print(feature_name_df.head())

   column_index        column_name
0             1  tBodyAcc-mean()-X
1             2  tBodyAcc-mean()-Y
2             3  tBodyAcc-mean()-Z
3             4   tBodyAcc-std()-X
4             5   tBodyAcc-std()-Y


In [2]:
feature_name = feature_name_df.iloc[:, 1].values.tolist()
print(feature_name[:10])

['tBodyAcc-mean()-X', 'tBodyAcc-mean()-Y', 'tBodyAcc-mean()-Z', 'tBodyAcc-std()-X', 'tBodyAcc-std()-Y', 'tBodyAcc-std()-Z', 'tBodyAcc-mad()-X', 'tBodyAcc-mad()-Y', 'tBodyAcc-mad()-Z', 'tBodyAcc-max()-X']


In [3]:
feature_dup_df = feature_name_df.groupby('column_name').count()
print(feature_dup_df[feature_dup_df['column_index'] > 1 ].count())

column_index    42
dtype: int64


In [4]:
def get_new_feature_name_df(old_feature_name_df):
    feature_dup_df = pd.DataFrame(data=old_feature_name_df.groupby('column_name').cumcount(), 
                                  columns = ['dup_cnt'])
    feature_dup_df = feature_dup_df.reset_index()
    
    new_feature_name_df = pd.merge(old_feature_name_df.reset_index(), feature_dup_df, how='outer')
    new_feature_name_df['column_name'] = new_feature_name_df[['column_name', 'dup_cnt']].apply(lambda x : x[0]+'_'+str(x[1]) if x[1] > 0 else x[0], axis=1)
    new_feature_name_df = new_feature_name_df.drop(['index'], axis=1)
    return new_feature_name_df

def get_human_dataset():
    feature_name_df = pd.read_csv('./UCI HAR Dataset/features.txt', sep='\s+',
                              header=None, names=['column_index', 'column_name'])
    new_feature_name_df = get_new_feature_name_df(feature_name_df)
    
    feature_name = new_feature_name_df.iloc[:, 1].values.tolist()
    
    X_train = pd.read_csv('./UCI HAR Dataset/train/X_train.txt', sep='\s+', names=feature_name)
    X_test = pd.read_csv('./UCI HAR Dataset/test/X_test.txt', sep='\s+', names=feature_name)
    
    y_train = pd.read_csv('./UCI HAR Dataset/train/y_train.txt', sep='\s+', header=None, names=['action'])
    y_test = pd.read_csv('./UCI HAR Dataset/test/y_test.txt', sep='\s+', header=None, names=['action'])
    
    return X_train, X_test, y_train, y_test

In [5]:
X_train, X_test, y_train, y_test = get_human_dataset()
print('학습 피처 데이터셋 정보')
print(X_train.info())

학습 피처 데이터셋 정보
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7352 entries, 0 to 7351
Columns: 561 entries, tBodyAcc-mean()-X to angle(Z,gravityMean)
dtypes: float64(561)
memory usage: 31.5 MB
None


In [6]:
print(y_train['action'].value_counts())

6    1407
5    1374
4    1286
1    1226
2    1073
3     986
Name: action, dtype: int64


## RandomForest

In [7]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
import warnings
warnings.filterwarnings('ignore')

rf_clf = RandomForestClassifier(random_state=0)
rf_clf.fit(X_train, y_train)
rf_pred = rf_clf.predict(X_test)
rf_accuracy = accuracy_score(y_test, rf_pred)
print(rf_pred)
print('랜덤 포레스트 정확도: {:.4f}'.format(rf_accuracy))

[5 5 5 ... 2 2 2]
랜덤 포레스트 정확도: 0.9253


In [8]:
rf_clf.predict_proba(X_test)

array([[0.  , 0.  , 0.  , 0.1 , 0.89, 0.01],
       [0.  , 0.  , 0.  , 0.15, 0.85, 0.  ],
       [0.  , 0.  , 0.  , 0.08, 0.92, 0.  ],
       ...,
       [0.19, 0.73, 0.08, 0.  , 0.  , 0.  ],
       [0.36, 0.54, 0.1 , 0.  , 0.  , 0.  ],
       [0.43, 0.44, 0.13, 0.  , 0.  , 0.  ]])

## AdaBoost

In [9]:
from sklearn.ensemble import AdaBoostClassifier
import time

start_time = time.time()
ab_clf = AdaBoostClassifier(n_estimators=100, learning_rate=0.01, random_state=0)
ab_clf.fit(X_train, y_train)
ab_pred = ab_clf.predict(X_test)
ab_accuracy = accuracy_score(y_test, ab_pred)

print('에이다부스트 정확도: {:.4f}'.format(ab_accuracy))
print('에이다부스트 수행시간: {:.1f} 초'.format(time.time() - start_time))

에이다부스트 정확도: 0.7234
에이다부스트 수행시간: 35.7 초


In [10]:
ab_clf.predict_proba(X_test)

array([[5.45881046e-09, 1.78909812e-06, 2.42621209e-09, 3.73303942e-01,
        4.04795874e-01, 2.21898387e-01],
       [5.45881046e-09, 1.78909812e-06, 2.42621209e-09, 3.73303942e-01,
        4.04795874e-01, 2.21898387e-01],
       [8.84563631e-09, 1.14034127e-06, 3.17287659e-09, 3.77538849e-01,
        3.72485584e-01, 2.49974415e-01],
       ...,
       [4.05642676e-01, 3.43655925e-01, 2.45657315e-01, 5.20985789e-07,
        1.86499032e-09, 5.04356104e-03],
       [4.05642676e-01, 3.43655925e-01, 2.45657315e-01, 5.20985789e-07,
        1.86499032e-09, 5.04356104e-03],
       [4.05642676e-01, 3.43655925e-01, 2.45657315e-01, 5.20985789e-07,
        1.86499032e-09, 5.04356104e-03]])

## logistic regressor

In [11]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(random_state=0)
lr.fit(X_train, y_train)
lr_pred = lr.predict(X_test)
lr_acc = accuracy_score(y_test, lr_pred)

print('로지스틱 회귀 정확도: {:.4f}'.format(lr_acc))

로지스틱 회귀 정확도: 0.9586


In [12]:
lr.predict_proba(X_test)

array([[2.48042103e-08, 2.00975109e-08, 5.19835663e-09, 8.76441196e-05,
        9.99856544e-01, 5.57618556e-05],
       [2.95201722e-08, 2.45473674e-09, 1.42412778e-11, 6.13820127e-02,
        9.38361941e-01, 2.56013955e-04],
       [3.79294431e-09, 6.93463370e-12, 6.14480616e-12, 3.93228724e-02,
        9.60555196e-01, 1.21927867e-04],
       ...,
       [1.80662485e-03, 9.96918277e-01, 1.27287565e-03, 1.00258552e-07,
        2.10703401e-06, 1.48141803e-08],
       [1.05395103e-02, 9.86998666e-01, 2.45114919e-03, 6.35020981e-06,
        4.19440573e-06, 1.30325738e-07],
       [9.51361344e-02, 8.98298943e-01, 6.53102353e-03, 4.71699150e-06,
        2.88473716e-05, 3.34567788e-07]])

## Ensemble

In [13]:
class EnsembleClassifier:
    def __init__(self, models, voting='soft', weights=None):
        
        self.models = models
        self.voting = voting
        self.weights = weights
        
    def predict(self, X_test):
        rf_clf = self.models['rf']
        ab_clf = self.models['ab']
        lr = self.models['lr']
        
        rf_pred = rf_clf.predict_proba(X_test)
        ab_pred = ab_clf.predict_proba(X_test)
        lr_pred = lr.predict_proba(X_test)
        
        preds = np.array([rf_pred, ab_pred, lr_pred])
        
        if self.voting == 'soft':
            prediction = np.average(preds, axis=0, weights=self.weights)
        elif self.voting == 'hard':
            pass

        return prediction

In [23]:
models = {'rf' : rf_clf, 'ab' : ab_clf, 'lr' : lr}

ensemble = EnsembleClassifier(models, voting='soft', weights=[0.15, 0.34, 0.7])
preds = ensemble.predict(X_test)

In [24]:
accuracy = accuracy_score(y_test, preds.argmax(axis=1)+1)
print('앙상블 모델 정확도: {:.4f}'.format(accuracy))

앙상블 모델 정확도: 0.9600


In [22]:
w1 = np.random.uniform(0,1,100)
w2 = np.random.uniform(0,1,100)
w3 = np.random.uniform(0,1,100)

i=0
j=0
k=0
best_acc = 0
for i,j,k in zip(w1,w2,w3):
    ensemble = EnsembleClassifier(models, voting='soft', weights=[i, j, k])
    preds = ensemble.predict(X_test)
    accuracy = accuracy_score(y_test, preds.argmax(axis=1)+1)
    if accuracy > best_acc:
        best_acc = accuracy
        i = i
        j = j
        k = k
    print(i,j,k)
    print('앙상블 모델 정확도: {:.4f}'.format(accuracy))
    print()
    
print(i, j, k, best_acc)

0.6836741781038382 0.5561186536049937 0.7215855219185839
앙상블 모델 정확도: 0.9552

0.7798158215123618 0.19121880611738196 0.5311635479331407
앙상블 모델 정확도: 0.9542

0.5666072284191913 0.7955939520774212 0.008988466962183472
앙상블 모델 정확도: 0.9206

0.9022521641643833 0.1454466845770146 0.7008357826456696
앙상블 모델 정확도: 0.9549

0.8492018411213124 0.099273744830082 0.4553167205095836
앙상블 모델 정확도: 0.9525

0.950166804489832 0.5922147591303734 0.44016135340235296
앙상블 모델 정확도: 0.9481

0.8511515599243346 0.16472569720218921 0.5467018921143004
앙상블 모델 정확도: 0.9535

0.6393449914357444 0.9900161661305379 0.9862486331025236
앙상블 모델 정확도: 0.9579

0.9145320492371661 0.942823299996923 0.7509141565028982
앙상블 모델 정확도: 0.9539

0.1628200910501968 0.39833558720129925 0.34344473633730765
앙상블 모델 정확도: 0.9583

0.6557915861164347 0.4387394161931233 0.9259803777589959
앙상블 모델 정확도: 0.9583

0.14082716042354115 0.13177052284128188 0.8822356864805725
앙상블 모델 정확도: 0.9593

0.8207070289107975 0.5114878686144512 0.24505121239010919
앙상블 모델 정확도: 

In [16]:
i = 0
j = 0
k = 0
best_acc = 0.
for i in range(1,5):
    for j in range(1,5):
        for k in range(1,5):
            ensemble = EnsembleClassifier(models, voting='soft', weights=[i, j, k])
            preds = ensemble.predict(X_test)
            accuracy = accuracy_score(y_test, preds.argmax(axis=1)+1)
            if accuracy > best_acc:
                best_acc = accuracy
                i = i
                j = j
                k = k
            print(i,j,k)
            print('앙상블 모델 정확도: {:.4f}'.format(accuracy))
            print()

print(i, j, k, best_acc)

1 1 1
앙상블 모델 정확도: 0.9549

1 1 2
앙상블 모델 정확도: 0.9593

1 1 3
앙상블 모델 정확도: 0.9593

1 1 4
앙상블 모델 정확도: 0.9593

1 2 1
앙상블 모델 정확도: 0.9528

1 2 2
앙상블 모델 정확도: 0.9583

1 2 3
앙상블 모델 정확도: 0.9589

1 2 4
앙상블 모델 정확도: 0.9593

1 3 1
앙상블 모델 정확도: 0.9498

1 3 2
앙상블 모델 정확도: 0.9576

1 3 3
앙상블 모델 정확도: 0.9589

1 3 4
앙상블 모델 정확도: 0.9593

1 4 1
앙상블 모델 정확도: 0.9481

1 4 2
앙상블 모델 정확도: 0.9559

1 4 3
앙상블 모델 정확도: 0.9583

1 4 4
앙상블 모델 정확도: 0.9589

2 1 1
앙상블 모델 정확도: 0.9494

2 1 2
앙상블 모델 정확도: 0.9559

2 1 3
앙상블 모델 정확도: 0.9586

2 1 4
앙상블 모델 정확도: 0.9593

2 2 1
앙상블 모델 정확도: 0.9484

2 2 2
앙상블 모델 정확도: 0.9549

2 2 3
앙상블 모델 정확도: 0.9586

2 2 4
앙상블 모델 정확도: 0.9593

2 3 1
앙상블 모델 정확도: 0.9467

2 3 2
앙상블 모델 정확도: 0.9535

2 3 3
앙상블 모델 정확도: 0.9576

2 3 4
앙상블 모델 정확도: 0.9593

2 4 1
앙상블 모델 정확도: 0.9454

2 4 2
앙상블 모델 정확도: 0.9528

2 4 3
앙상블 모델 정확도: 0.9569

2 4 4
앙상블 모델 정확도: 0.9583

3 1 1
앙상블 모델 정확도: 0.9464

3 1 2
앙상블 모델 정확도: 0.9535

3 1 3
앙상블 모델 정확도: 0.9566

3 1 4
앙상블 모델 정확도: 0.9579

3 2 1
앙상블 모델 정확도: 0.9464

3 2 2
앙상블 모델 정확도: 0.9525

3 2 3
앙상블 모델